# Generated by Django 3.1.4 on 2020-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Inverter', 'Inverter'), ('MPPT', 'MPPT'), ('Montoring', 'Montoring'), ('Solar Controller', 'Solar Controller')], max_length=200, null=True),
        ),
    ]
